site_name: Luiger Pages
nav:
    - Inicio: index.md
    - Mi Blog:
        - La Dureza Necesaria - El Desafío de Ser Objetivo Cuando Eres Empático: blog/2026/0304/empatia-objetividad.md
        - La Importancia del Descanso: blog/2026/0201/descanso.md
        - 2026 El año en que debemos estudiar más: blog/2025/1225/estudiar2025.md
        - La AI como parte de nuestro aprendizaje: blog/2024/0809/ai.md
        - Como sacar el pasaporte en el Tachira: blog/2022/2603/pasaporte.md
        - Año Nuevo: blog/2020/0101/nuevo.md
    - Mis articulos:
        - Microservicios: articulos/2019/MicroSOA/micro2soa.md
    - Acerca de mi: about.md
    
theme:
    name: material
