site_name: Luiger Pages
nav:
    - Inicio: index.md
    - Mi Blog: 
        - Año Nuevo: blog/2020/0101/nuevo.md
    - Mis articulos:
        - Microservicios: articulos/2019/MicroSOA/micro2soa.md
    - Acerca de mi: about.md
    
theme: material