site_name: Luiger Pages
nav:
    - Inicio: index.md
    - Mi Blog: 
        - Año Nuevo: blog/2020/0101/nuevo.md
        - Nueva normalidad: blog/2020/0606/nuevanormalidad.md
        - Como sacar el pasaporte en el Tachira: blog/2022/2603/pasaporte.md
    - Mis articulos:
        - Microservicios: articulos/2019/MicroSOA/micro2soa.md
    - Acerca de mi: about.md
    
theme: windmill